#!/bin/sh
docker start tracker
docker exec tracker fdfs_trackerd /home/fastdfs/fastdfs-5.05/conf/tracker.conf
docker exec tracker /usr/local/nginx/sbin/nginx
docker exec tracker cat /usr/local/nginx/logs/error.log
docker exec tracker netstat -ant | grep 22122
docker exec tracker cat /home/fastdfs_file/logs/trackerd.log
